### PR TITLE
Feat/import reply

### PR DESCRIPTION
**Pull request by wicogohome**
Hello @marcomaroni-github , I'm Wico. Thank you for creating this repository.
It saved me a lot of time to import my tweets into bsky.

Also, I added a import reply function to help me move more smoothly. So if you think it is a feature that could make some help, please let me know. I will update the README after you check. Thanks.

## ENV

- `IMPORT_REPLY` = if set to "1" , it will import your reply to bsky too.
- `IMPORT_REPLY_USER_ID`=  Your Twitter user id, a string of numbers (ex. 1612345678 ). To filter the reply is to your account. ( ※ I'm not sure if is needy.)

## Changes
1. `getTweets()`：I added a file (`TWEETS_MAPPING_FILE_NAME` ) to store the tweets & bsky ids mapping, so we can pause the import and then restart without duplicated import.
2. `bskyReply.ts`:`getReplyRefs()`：It will return the root & parent references by searching the tweets (it should be updated with bsky mapping)
3. `main()`：
    1.  It will skip the data that has the `bsky` attribute.
    2.  If IMPORT_REPLY = "1" and SIMULATE="1",  it will use `getReplyRefs()` to get reply refs. 
    3. After creating bsky post, it will update the bsky data into `sortedTweets`, so we can search parent & root by using `getReplyRefs()` .
    4.  try catch finally: Finally, it will update `sortedTweets`  into the mapping file.

### CODE REVIEW

**Comment by marcomaroni-github** [comment]
Hi @wicogohome , thank you very much for your contribution.
A request, since the PAST_HANDLES setting is already present, in which to insert your twitter handle (to exclude the links to yourself that are put in the text of the archive tweets) it would be useful to use that variable (which can contain one or more handles) in your getReplyRefs() function.

**Comment by wicogohome** [comment]
> Hi @wicogohome , thank you very much for your contribution. A request, since the PAST_HANDLES setting is already present, in which to insert your twitter handle (to exclude the links to yourself that are put in the text of the archive tweets) it would be useful to use that variable (which can contain one or more handles) in your getReplyRefs() function.

Did you mean that we should use the PAST_HANDLES to handle the [Quote Posts](https://docs.bsky.app/blog/create-post#quote-posts) too ? 
I thought it would be a good idea. Let me try it.

**Comment by marcomaroni-github** [comment]
> > Hi @wicogohome , thank you very much for your contribution. A request, since the PAST_HANDLES setting is already present, in which to insert your twitter handle (to exclude the links to yourself that are put in the text of the archive tweets) it would be useful to use that variable (which can contain one or more handles) in your getReplyRefs() function.
> 
> Did you mean that we should use the PAST_HANDLES to handle the [Quote Posts](https://docs.bsky.app/blog/create-post#quote-posts) too ? I thought it would be a good idea. Let me try it.

Yes

**Comment by wicogohome** [comment]
Hi @marcomaroni-github , I have updated the code. 

There are some more changes:
1. Rename `'bskyReply.ts`' to '`bskyParams.ts`': This will allow us to handle additional param format functions in this file.
2. Add '`getEmbeddedUrlAndRecord()`': It will get the last url to embed and provide the original tweet url and bsky record data.
3. Add '`getMergeEmbed()`': Because bsky and twitter might be hybrid-embedded, I wrote this method to handle images and record embed data.
4. Add '`urlHandler.ts`': I relocated the PAST_HANDLES process to 'checkPastHandles()' and added the  `https://twitter.com/{handle}` check.
5. Change '`cleanTweetText()`' to swap the self-quote tweet url with bsky url while excluding embeddedUrl.
This is an example of multiple links.
```
tweet input:

tweet_link1
tweet_link2
tweet_link3
```
```
bsky output:

bsky_link1
bsky_link2
(bsky_link3 quote)
```
7. Modify the way to get newUrl: I updated it to search the '`urlMappings`' first. So we can ensure the result is the same as the origin.
8. (for dev)bskyAPI: deleteBskyPosts : If something goes wrong, call this method to clear the previously imported posts.

**Comment by marcomaroni-github** [comment]
Hi @wicogohome I'll made some test next a merge into main branch

**Comment by wicogohome** [comment]
> Hi @wicogohome I made some changes to use PAST_HANDLES instead of the new IMPORT_REPLY_USER_ID parameter since it is possible to do the check also with the screename and the user id is not immediately available for users. I also made the ability to import replicas by default, with the possibility of disabling them with the use of the DISABLE_IMPORT_REPLY parameter
> 
> Maybe you can do some tests too, everything is already in the DEV branch, so then I'll merge into the main branch and release a new version with all these changes.
> 
> Thanks

Hello, @marcomaroni-github. Thank you for the revisions. I think the DISABLE_IMPORT_REPLY is excellent.
However, we should verify each PAST_HANDLE.
I have corrected it with https://github.com/marcomaroni-github/twitter-to-bluesky/pull/19. Thanks!

**Pull request merged**
